name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=12.0

    - name: Setup .NET Core SDK 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: |
        nuget restore TestApp1/TestApp1/TestApp1.csproj
        nuget restore TestApp1/TestApp1.Android/TestApp1.Android.csproj

    - name: Build
      run: |
        msbuild TestApp1/TestApp1.Android/TestApp1.Android.csproj /t:PackageForAndroid /p:Configuration=Release
        cp TestApp1/TestApp1.Android/bin/Release/com.beeradmoore.testapp1.apk TestApp1/TestApp1.Android/obj/Release/com.beeradmoore.testapp1.${{ github.run_number }}-unsigned.apk
    
    - name: Sign build
      run: |
        $ANDROID_HOME/build-tools/32.0.0/zipalign -p -f -v 4 TestApp1/TestApp1.Android/bin/Release/com.beeradmoore.testapp1.apk TestApp1/TestApp1.Android/obj/Release/com.beeradmoore.testapp1.${{ github.run_number }}-aligned.apk

    - name: Upload build 
      uses: actions/upload-artifact@v2
      with:
        name: TestApp1-build-${{ github.run_number }}
        path: |
          TestApp1/TestApp1.Android/obj/Release/com.beeradmoore.testapp1.${{ github.run_number }}-unsigned.apk
          TestApp1/TestApp1.Android/obj/Release/com.beeradmoore.testapp1.${{ github.run_number }}-aligned.apk

