name: Build Xamarin.iOS app

on: [workflow_dispatch]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=15.2
    
    - name: Set default Xcode 13.1
      run: |
        XCODE_ROOT=/Applications/Xcode_13.1.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: |
        nuget restore TestApp1/TestApp1/TestApp1.csproj
        nuget restore TestApp1/TestApp1.iOS/TestApp1.iOS.csproj

    - name: Build
      run: msbuild TestApp1/TestApp1.iOS/TestApp1.iOS.csproj /p:Configuration=Release /p:Platform=iPhone /t:Rebuild